### ISSUE TITLE
convert contentEncoding: base64 to format: bass64

### ISSUE THREAD

**Issue by DavidBiesack** [apiture/openapi-down-convert#13]
when a schema uses
```yaml
type: string
contentEncoding: base64
```

this should be converted to
```yaml
type: string
format: base64
```

Source: https://www.openapis.org/blog/2021/02/16/migrating-from-openapi-3-0-to-3-1-0

similarly,
```yaml
  content:
    application/octet-stream: {}
```

should be down-converted to 

```yaml
  content:
    application/octet-stream:
      schema:
        type: string
        format: binary
```
